// Global using directives

global using System.Linq.Dynamic.Core;
global using System.Reflection;
global using System.Runtime.Loader;
global using System.Security.Cryptography;
global using System.Text;
global using System.Text.Json.Serialization;
global using Ardalis.GuardClauses;
global using Blazored.LocalStorage;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using Lamar;
global using LowlandTech.Core.Abstractions;
global using LowlandTech.Core.Attributes;
global using LowlandTech.Core.Domain.Enums;
global using LowlandTech.Core.Domain.Types;
global using LowlandTech.Core.Extensions;
global using LowlandTech.Core.Types;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Components;
global using Microsoft.AspNetCore.Components.Routing;
global using Microsoft.AspNetCore.Hosting;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Diagnostics;
global using Microsoft.EntityFrameworkCore.Infrastructure;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using MudBlazor;
global using IContainer = Lamar.IContainer;