name: LowlandTech.Core

on:
  push:
    branches:
      - develop
      - main
    tags:
      - '*' # Trigger on any tag creation
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup .NET SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # Use the latest .NET 8 version

      # Install GitVersion
      - name: Install GitVersion
        uses: gittools/actions/gitversion/execute@v0
        id: gitversion

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore src/lowlandtech.core

      # Build the project
      - name: Build
        run: dotnet build src/lowlandtech.core --no-restore --configuration Release

      # Run tests
      - name: Run Tests
        run: dotnet test src/lowlandtech.core --no-restore --configuration Release --verbosity normal

      # Pack the NuGet package (for tags only)
      - name: Pack NuGet package
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          dotnet pack src/lowlandtech.core --no-restore --no-build --configuration Release -o ./nuget /p:PackageVersion=${{ steps.gitversion.outputs.nugetVersion }}

      # Publish the NuGet package (for tags only)
      - name: Publish NuGet package
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dotnet nuget push ./nuget/*.nupkg --source https://nuget.pkg.github.com/lowlandtech/index.json --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
