name: LowlandTech.Core

on:
  push:
    branches:
      - develop
      - main
      - 'release/*'  # Trigger on any release branch like release/1.0.1
    tags:
      - '*'  # Trigger on any tag creation
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code with full history to prevent shallow clone issues
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch the full history to ensure GitVersion works properly

      # Setup .NET SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # Use the latest .NET 8 version

      # Install GitVersion as a dotnet global tool
      - name: Install GitVersion
        run: dotnet tool install --global GitVersion.Tool

      # Ensure the GitVersion tool path is in PATH
      - name: Add GitVersion to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      # Run GitVersion to determine version
      - name: Run GitVersion
        run: dotnet-gitversion /output json /output buildserver
        id: gitversion

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore src/lowlandtech.core

      # Build the project
      - name: Build
        run: dotnet build src/lowlandtech.core --no-restore --configuration Release

      # Run tests
      - name: Run Tests
        run: dotnet test src/lowlandtech.core --no-restore --configuration Release --verbosity normal

      # Pack the NuGet package (for release branches and tags)
      # - name: Pack NuGet package
      #   if: startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads/release/')
      #   run: |
      #     dotnet pack src/lowlandtech.core --no-restore --no-build --configuration Release -o ./nuget

      # Publish the NuGet package (only on the main branch)
      - name: Publish NuGet package
        if: github.ref == 'refs/heads/main'
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
         dotnet pack src/lowlandtech.core --no-restore --no-build --configuration Release -o ./nuget
         dotnet nuget push ./nuget/*.nupkg --source https://nuget.pkg.github.com/lowlandtech/index.json --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
